languageCode = "en-us"
title = "IamZS"
baseurl = "https://fduzs.github.io"
disableKinds = ["sitemap", "RSS"]

[params]
  name = "Shuai Zheng"
  about = "nobody"
  copyright = "SeisMan 2013 - 2020"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Academic"
  icon = "university"
  link = "ac"

[[params.social]]
  medium = "Blog"
  icon = "edit"
  link = "blog"

[[params.social]]
  medium = "Wiki"
  icon = "book"
  link = "wiki"

#[[params.social]]
#  medium = "Github"
#  icon = "github"
#  link = "###"

#[[params.social]]
#  medium = "Email"
#  icon = "envelope-o"
#  link = "mailto:seisman.info@gmail.com"
